---

########################################################################
# Generate migration Jenkins jobs.
########################################################################

- name: Create a list of AEM In-Place Upgrade jobs for AWS
  shell: echo {{ item.path }}
  with_filetree: ../../../provisioners/jenkins/jenkinsfiles/aem-opencloud/migration/aws/
  when: item.state == 'file' and item.path is match('.*aem-upgrade-in-place')
  register: migration_aem_upgrade_in_place_jobs

- name: Trim skipped AEM Upgrade jobs for AWS
  set_fact:
    migration_aem_upgrade_in_place_jobs_trimmed: "{{ migration_aem_upgrade_in_place_jobs | trim_skipped() }}"

- name: Create a list of AEM EXPPORT IMPORT Upgrade jobs for AWS
  shell: echo {{ item.path }}
  with_filetree: ../../../provisioners/jenkins/jenkinsfiles/aem-opencloud/migration/aws/
  when: item.state == 'file' and item.path is match('.*aem-upgrade-export-import')
  register: migration_aem_upgrade_export_import_jobs

- name: Trim skipped AEM Upgrade jobs for AWS
  set_fact:
    migration_aem_upgrade_export_import_jobs_trimmed: "{{ migration_aem_upgrade_export_import_jobs | trim_skipped() }}"

- name: Create a list of AEM Reconfiguration jobs for AWS
  shell: echo {{ item.path }}
  with_filetree: ../../../provisioners/jenkins/jenkinsfiles/aem-opencloud/migration/aws/
  when: item.state == 'file' and item.path is match('.*aem-reconfiguration')
  register: migration_aem_reconfiguration_jobs

- name: Trim skipped AEM Reconfiguration jobs for AWS
  set_fact:
    migration_aem_reconfiguration_jobs_trimmed: "{{ migration_aem_reconfiguration_jobs | trim_skipped() }}"

- name: "Generate jobs for AEM In-Place upgrade migration configuration profile directories"
  file:
    path: ../../../stage/jenkins/jobs/aem-opencloud-{{ aem_opencloud.version }}/migration/aws/{{ item[0].item.path }}-{{ item[2].item.path }}/{{ item[1].item.path }}/
    state: directory
    mode: '0776'
  with_nested:
    - "{{ aem_aws_stack_builder_aem_upgrade_in_place_profiles_trimmed.results }}"
    - "{{ migration_aem_upgrade_in_place_jobs_trimmed.results }}"
    - "{{ aem_stack_manager_messenger_profiles_trimmed.results }}"

- name: "Generate jobs for AEM EXPORT IMPORT upgrade migration configuration profile directories"
  file:
    path: ../../../stage/jenkins/jobs/aem-opencloud-{{ aem_opencloud.version }}/migration/aws/{{ item[0].item.path }}-{{ item[1].item.path }}-{{ item[3].item.path }}/{{ item[2].item.path }}/
    state: directory
    mode: '0776'
  with_nested:
    - "{{ aem_aws_stack_builder_aem_upgrade_export_profiles_trimmed.results }}"
    - "{{ aem_aws_stack_builder_aem_upgrade_import_profiles_trimmed.results }}"
    - "{{ migration_aem_upgrade_export_import_jobs_trimmed.results }}"
    - "{{ aem_stack_manager_messenger_profiles_trimmed.results }}"

- name: "Generate jobs for AEM reconfiguration migration configuration profile directories"
  file:
    path: ../../../stage/jenkins/jobs/aem-opencloud-{{ aem_opencloud.version }}/migration/aws/{{ item[0].item.path }}-{{ item[2].item.path }}/{{ item[1].item.path }}/
    state: directory
    mode: '0776'
  with_nested:
    - "{{ aem_aws_stack_builder_aem_reconfiguration_profiles_trimmed.results }}"
    - "{{ migration_aem_reconfiguration_jobs_trimmed.results }}"
    - "{{ aem_stack_manager_messenger_profiles_trimmed.results }}"

- name: "Generate jobs for AEM upgrade In-Place migration configuration profile config.xml for AEM upgrade migration configuration profile components"
  template:
    src: '../../../templates/ansible/jenkins/config/category-config-profile.xml.j2'
    dest: ../../../stage/jenkins/jobs/aem-opencloud-{{ aem_opencloud.version }}/migration/aws/{{ item[0].item.path }}-{{ item[2].item.path }}/config.xml
    mode: '0644'
  with_nested:
    - "{{ aem_aws_stack_builder_aem_upgrade_in_place_profiles_trimmed.results }}"
    - "{{ migration_aem_upgrade_in_place_jobs_trimmed.results }}"
    - "{{ aem_stack_manager_messenger_profiles_trimmed.results }}"

- name: "Generate jobs for AEM EXPORT IMPORT upgrade migration configuration profile config.xml for AEM upgrade migration configuration profile components"
  template:
    src: '../../../templates/ansible/jenkins/config/category-config-profile-aem-upgrade-export-import.xml.j2'
    dest: ../../../stage/jenkins/jobs/aem-opencloud-{{ aem_opencloud.version }}/migration/aws/{{ item[0].item.path }}-{{ item[1].item.path }}-{{ item[3].item.path }}/config.xml
    mode: '0644'
  with_nested:
    - "{{ aem_aws_stack_builder_aem_upgrade_export_profiles_trimmed.results }}"
    - "{{ aem_aws_stack_builder_aem_upgrade_import_profiles_trimmed.results}}"
    - "{{ migration_aem_upgrade_export_import_jobs_trimmed.results }}"
    - "{{ aem_stack_manager_messenger_profiles_trimmed.results }}"

- name: "Generate jobs for AEM reconfiguration configuration profile config.xml for AEM upgrade migration configuration profile components"
  template:
    src: '../../../templates/ansible/jenkins/config/category-config-profile.xml.j2'
    dest: ../../../stage/jenkins/jobs/aem-opencloud-{{ aem_opencloud.version }}/migration/aws/{{ item[0].item.path }}-{{ item[2].item.path }}/config.xml
    mode: '0644'
  with_nested:
    - "{{ aem_aws_stack_builder_aem_reconfiguration_profiles_trimmed.results }}"
    - "{{ migration_aem_reconfiguration_jobs_trimmed.results }}"
    - "{{ aem_stack_manager_messenger_profiles_trimmed.results }}"

- name: "Generate jobs for AEM In-Place upgrade migration config.xml for AEM upgrade migration configuration profile components"
  vars:
    aem_architecture_type: consolidated
  template:
    src: ../../../templates/ansible/jenkins/config/jobs-migration-aem-upgrade-in-place.xml.j2
    dest: ../../../stage/jenkins/jobs/aem-opencloud-{{ aem_opencloud.version }}/migration/aws/{{ item[0].item.path }}-{{ item[2].item.path }}/{{ item[1].item.path }}/config.xml
    mode: '0644'
  with_nested:
    - "{{ aem_aws_stack_builder_aem_upgrade_in_place_profiles_trimmed.results }}"
    - "{{ migration_aem_upgrade_in_place_jobs_trimmed.results }}"
    - "{{ aem_stack_manager_messenger_profiles_trimmed.results }}"

- name: "Generate jobs for AEM EXPORT IMPORT upgrade migration config.xml for AEM upgrade migration configuration profile components"
  vars:
    aem_architecture_type: consolidated
  template:
    src: ../../../templates/ansible/jenkins/config/jobs-migration-aem-upgrade-export-import.xml.j2
    dest: ../../../stage/jenkins/jobs/aem-opencloud-{{ aem_opencloud.version }}/migration/aws/{{ item[0].item.path }}-{{ item[1].item.path }}-{{ item[3].item.path }}/{{ item[2].item.path }}/config.xml
    mode: '0644'
  with_nested:
    - "{{ aem_aws_stack_builder_aem_upgrade_export_profiles_trimmed.results }}"
    - "{{ aem_aws_stack_builder_aem_upgrade_import_profiles_trimmed.results}}"
    - "{{ migration_aem_upgrade_export_import_jobs_trimmed.results }}"
    - "{{ aem_stack_manager_messenger_profiles_trimmed.results }}"

- name: "Generate jobs for AEM reconfiguration config.xml for AEM reconfiguration migration configuration profile components"
  template:
    src: ../../../templates/ansible/jenkins/config/jobs-migration-aem-reconfiguration.xml.j2
    dest: ../../../stage/jenkins/jobs/aem-opencloud-{{ aem_opencloud.version }}/migration/aws/{{ item[0].item.path }}-{{ item[2].item.path }}/{{ item[1].item.path }}/config.xml
    mode: '0644'
  with_nested:
    - "{{ aem_aws_stack_builder_aem_reconfiguration_profiles_trimmed.results }}"
    - "{{ migration_aem_reconfiguration_jobs_trimmed.results }}"
    - "{{ aem_stack_manager_messenger_profiles_trimmed.results }}"
